# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  # schedule:
    # This will run every day at 09:30 UTC+7
    # - cron: '30 2 * * *'
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Run
        env:
          API_BASE_URL: ${{ vars.API_BASE_URL }}
        run: go run ./cmd/quote

      - name: Configure git
        run: |
          git config --global user.name "Dien Vo"
          git config --global user.email "dien.vo@andpad.co.jp"

      - name: Add README.md
        run: git add README.md

      - name: Commit changes
        run: git commit -m "Update README.md with a new quote"

      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
